In [2]:
import stk
import torch

In [38]:
tensor = torch.randn((64, 64), dtype=torch.float16, device='cuda')
mask = torch.randint(size=(4, 4), low=0, high=2).kron(torch.ones((16, 16))).to(dtype=bool, device="cuda")
tensor = torch.where(mask, tensor, 0)

In [39]:
kek = stk.ops.to_sparse(tensor, blocking=16)

In [40]:
kek.data.numel()

2560

In [42]:
kek.data.shape

torch.Size([10, 16, 16])

In [43]:
mask[::16, ::16]

tensor([[ True,  True, False, False],
        [ True, False,  True, False],
        [ True,  True, False,  True],
        [ True,  True, False,  True]], device='cuda:0')

In [44]:
kek.offsets

tensor([ 0,  2,  4,  7, 10], device='cuda:0', dtype=torch.int32)

In [45]:
kek.column_indices

tensor([0, 1, 0, 2, 0, 1, 3, 0, 1, 3], device='cuda:0', dtype=torch.int16)

In [47]:
kek.row_indices

tensor([0, 0, 1, 1, 2, 2, 2, 3, 3, 3], device='cuda:0', dtype=torch.int16)

In [49]:
kek.size()

torch.Size([64, 64])

In [73]:
BS = 16
R = 4 * BS
batch_size = 5 * BS
labels = [
    [2, 3], [1], [2, 3], [0], [1]
]

data = torch.randn((7, 16, 16), dtype=torch.float16).to('cuda')

column_indices = sum(labels, [])
row_indices = []
offsets = [0]
for i, lb in enumerate(labels):
    for l in lb:
        row_indices.append(i)
    offsets.append(len(row_indices))

column_indices = torch.tensor(column_indices).to('cuda', dtype=torch.int16)
row_indices = torch.tensor(row_indices).to('cuda', dtype=torch.int16)
offsets = torch.tensor(offsets).to('cuda', dtype=torch.int32)

In [74]:
mat = stk.Matrix((batch_size, R), data=data, row_indices=row_indices, column_indices=column_indices, offsets=offsets)

In [75]:
mat.validate()

In [79]:
a, b, c = data.shape

In [82]:
import numpy as np
np.concat(([0], [2, 3]))

array([0, 2, 3])